Added butler download.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -36,64 +36,51 @@ env:
 script:
  - travis_retry make all-dependencies
  - make all
-# - test "$TRAVIS_OS_NAME" == "linux" && make check || echo "Skipping check"
-# - test "$TRAVIS_OS_NAME" == "linux" && make check-scripts || echo "Skipping scripts check"
-# - test "$TRAVIS_OS_NAME" == "linux" && make test || echo "Skipping tests"
-# - test "$TRAVIS_OS_NAME" == "linux" && make nunit || echo "Skipping nunit tests"
+ - test "$TRAVIS_OS_NAME" == "linux" && make check || echo "Skipping check"
+ - test "$TRAVIS_OS_NAME" == "linux" && make check-scripts || echo "Skipping scripts check"
+ - test "$TRAVIS_OS_NAME" == "linux" && make test || echo "Skipping tests"
+ - test "$TRAVIS_OS_NAME" == "linux" && make nunit || echo "Skipping nunit tests"
 
-after_script:
- - export TRAVIS_TAG=tiberiansun-$TRAVIS_BUILD_ID
+# Only watch the development branch and tagged release.
+branches:
+ only:
+   - /^release-.*$/
+   - /^playtest-.*$/
+   - /^pkgtest-.*$/
+   - /^prep-.*$/
+   - bleed
 
+# Notify developers when build passed/failed.
+notifications:
+  irc:
+    template:
+      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
+    channels:
+      - "irc.freenode.net#openra"
+    use_notice: true
+    skip_join: true
+
+before_deploy:
+ - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
+     wget https://mirrors.edge.kernel.org/ubuntu/pool/universe/n/nsis/nsis-common_3.04-1_all.deb;
+     wget https://mirrors.edge.kernel.org/ubuntu/pool/universe/n/nsis/nsis_3.04-1_amd64.deb;
+     sudo dpkg -i nsis-common_3.04-1_all.deb;
+     sudo dpkg -i nsis_3.04-1_amd64.deb;
+     cd packaging && ./update-wiki.sh ${TRAVIS_TAG} && cd ..;
+   fi;
  - export PATH=$PATH:$HOME/usr/bin
  - DOTVERSION=`echo ${TRAVIS_TAG} | sed "s/-/\\./g"`
  - cd packaging
  - mkdir build
  - ./package-all.sh ${TRAVIS_TAG} ${PWD}/build/
-
- - ls
- - ls ./build
-
-# Only watch the development branch and tagged release.
-branches:
- only:
-   #- /^release-.*$/
-   #- /^playtest-.*$/
-   #- /^pkgtest-.*$/
-   #- /^prep-.*$/
-   #- bleed
-   - tiberiansun
-
-# Notify developers when build passed/failed.
-#notifications:
-#  irc:
-#    template:
-#      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
-#    channels:
-#      - "irc.freenode.net#openra"
-#    use_notice: true
-#    skip_join: true
-
-#before_deploy:
-# - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
-#     wget https://mirrors.edge.kernel.org/ubuntu/pool/universe/n/nsis/nsis-common_3.04-1_all.deb;
-#     wget https://mirrors.edge.kernel.org/ubuntu/pool/universe/n/nsis/nsis_3.04-1_amd64.deb;
-#     sudo dpkg -i nsis-common_3.04-1_all.deb;
-#     sudo dpkg -i nsis_3.04-1_amd64.deb;
-#     cd packaging && ./update-wiki.sh ${TRAVIS_TAG} && cd ..;
-#   fi;
-# - export PATH=$PATH:$HOME/usr/bin
-# - DOTVERSION=`echo ${TRAVIS_TAG} | sed "s/-/\\./g"`
-# - cd packaging
-# - mkdir build
-# - ./package-all.sh ${TRAVIS_TAG} ${PWD}/build/
-#deploy:
-#  provider: releases
-#  api_key:
-#    secure: "g/LU11f+mjqv+lj0sR1UliHwogXL4ofJUwoG5Dbqlvdf5UTLWytw/OWSCv8RGyuh10miyWeaoqHh1cn2C1IFhUEqN1sSeKKKOWOTvJ2FR5mzi9uH3d/MOBzG5icQ7Qh0fZ1YPz5RaJJhYu6bmfvA/1gD49GoaX2kxQL4J5cEBgg="
-#  file_glob: true
-#  file: build/*
-#  skip_cleanup: true
-#  on:
-#    all_branches: true
-#    tags: true
-#    repo: OpenRA/OpenRA
+deploy:
+  provider: releases
+  api_key:
+    secure: "g/LU11f+mjqv+lj0sR1UliHwogXL4ofJUwoG5Dbqlvdf5UTLWytw/OWSCv8RGyuh10miyWeaoqHh1cn2C1IFhUEqN1sSeKKKOWOTvJ2FR5mzi9uH3d/MOBzG5icQ7Qh0fZ1YPz5RaJJhYu6bmfvA/1gD49GoaX2kxQL4J5cEBgg="
+  file_glob: true
+  file: build/*
+  skip_cleanup: true
+  on:
+    all_branches: true
+    tags: true
+    repo: OpenRA/OpenRA
